import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {flex: 1},
  sortDateContainer: {
    backgroundColor: '#222B45',
    height: 110,
    width: '100%',
    flexDirection: 'row',
    padding: 20,
    alignItems: 'center',
    justifyContent: 'space-around',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    marginTop: -30,
    position: 'absolute',
    zIndex: 1,
  },
  dateContainer: {alignItems: 'center'},
  date: {color: 'white'},
  containerdown: {flex: 1},
  eventContainer: {
    backgroundColor: '#FCFCFC',
    width: '100%',
    flexDirection: 'row',
    padding: 10,
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    marginTop: 50,
    paddingHorizontal: 20,
    position: 'absolute',
    zIndex: 2,
  },
  card: {
    width: 160,
    height: 276,
    marginHorizontal: 15,
    marginTop: 100,
  },
});
